#------------------------------------开发环境配置---------------------------------
spring:
  #开发环境-数据库连接配置
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/bishis_pay?useUnicode=true&characterEncoding=utf-8
     username: root
     password: xiuxiu
     driver-class-name: com.mysql.jdbc.Driver
     type: com.zaxxer.hikari.HikariDataSource
     hikari:
        #公式：connections =cpu核心数*2 + 硬盘数
        maximum-pool-size: 15
        max-lifetime: 60000
########################附件配置########################
file:
  mapping: http://127.0.0.1:8083/FaceDr/static/downFile
  path: D:\\projects
###################开启发开发者模(取消登录验证)#############
devmode: true