########################spring配置########################
spring:
  #dev,prod 测试环境,生产环境
  profiles:
    active: dev
  #jackson日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #附件上传大小限制
  servlet:
    multipart:
      max-file-size: 3000MB
      max-request-size: 3000MB
  #开启热部署
  devtools:
    restart:
      enabled: false
########################thymeleaf########################
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
########################Tomcat配置########################
server:
  port: 8084
  error:
      whitelabel:
        enabled: false
  servlet:
    context-path: /
    application-display-name: bishisPay
#########################mybatis-plus配置########################
mybatis-plus:
  mapper-locations: classpath:/com/bshis/pay/mapper/xml/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.bshis.pay.entity,com.bshis.pay.mapper
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: false
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


########################日志配置########################
logging:
  file: logs/face_doctor.log
  level:
    com.lxkj.mapper: DEBUG
    com.github.binarywang.wxpay: DEBUG
  pattern:
    dateformat:  yyyy/MM/dd HH:mm:ss
########################微信相关配置########################
wechat:
  app_id: wx10ccc6944148ce66
  app_secret: 3f4041182318994c275e05a7cedb5abd
  pay:
    appId: wx10ccc6944148ce66
    mchId: 1501403451
    mchKey: nkhiedgyvhoploi879gjvnguiomsxtbg
    keyPath: classpath:config/apiclient_cert.p12